[package]
name = "daachorse"
version = "0.4.0"
edition = "2021"
authors = [
    "Koichi Akabe <vbkaisetsu@gmail.com>",
    "Shunsuke Kanda <shnsk.knd@gmail.com>",
]
description = "Daachorse: Double-Array Aho-Corasick"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/legalforce-research/daachorse"
repository = "https://github.com/legalforce-research/daachorse"
readme = "README.md"
keywords = ["string", "search", "text", "aho", "multi"]
categories = ["text-processing"]
exclude = [".*"]

[dependencies]

[dev-dependencies]
rand = "0.8.4"  # MIT or Apache-2.0

[workspace]
members = [
    "bench",
    "daacfind",
]
